### ISSUE TITLE
Injected Messages class not returning localized string

### ISSUE THREAD

**Issue by wildunne** [svenkubiak/mangooio#233]
${18n("key")} is correctly returning the localized text when the cookie is set, but this isn't:

    @Inject
    Messages msg;

    public String getString(String key) {
        return msg.get(key, Optional.of("de"));
    }

As far as I can see, this should be working, at least according to the docs. Is there any way to force the language?

In this case it should be working as the i18n cookie is being set. Also Locale.setDefault is not having the effect here either.

**Comment by MarkVink** [comment]
https://github.com/svenkubiak/mangooio/blob/master/mangooio-core/src/main/java/io/mangoo/i18n/Messages.java

Looking to the source code, the arguments after the key can be used as parameter in the translated text itself. It seems there isn't a way to force the language for one particular message. Although it would be possible to call the reload() method in order to load another language file.

**Comment by svenkubiak** [comment]
Mark is correct. The reload method is used to force language change for a given Message instance. The second paramter is used to pass optional parameters into the translation, like:

```
This {0} is very {1}

msg.get(key, chesse, good) -> This cheese is very good
```

**Comment by svenkubiak** [comment]
Is this still an issue or can I close it?

**Comment by wildunne** [comment]
Resolved by modifying the locale handler

https://thethug.life/overwriting-a-handler-in-mangoo/
