### ISSUE TITLE
Advantages over Ninja?

### ISSUE THREAD

**Issue by jjlauer** [svenkubiak/mangooio#55]
Hey,

I liked a lot of your contributions to the Ninja framework.  Noticed you built a new framework and obviously have put a lot of time into it. Curious what drove to write your own vs. drive change within Ninja project?  It looks like there are some great ideas (e.g. admin pages, Undertow, non-servlet-based), but the heart of it seems similar.

Just trying to understand the ultimate goal.

Thx.

**Comment by svenkubiak** [comment]
Hey Joe,

what drove me at start, was that I had some spare time and ran into Undertow. From there it was "how difficult could it be to build something like ninja based on other technologies". That is basically the hole story. I think for me it was easier to start from scratch rather than dig into the Ninja core code.  It was always my intention to built something familiar to ninja, as I really liked the ideas that evolved from play and were added from Raphael and the rest of the ninja community. For the future I see Ninja and mangoo I/O as siblings - with mangoo I/O being the little brother :-D

Cheers,
Sven
